import type { GalaxyData } from './galaxy'

/** Compile-time shape check for §4 types (replaces importing multi-MB public JSON). */
export const galaxyMinimalFixture = {
  meta: {
    version: 'fixture',
    generated_at: '1970-01-01T00:00:00Z',
    count: 1,
    embedding_model: 'fixture',
    umap_params: {
      n_neighbors: 15,
      min_dist: 0.1,
      metric: 'cosine',
      random_state: 42,
      densmap: true,
    },
    genre_weight_ratio: 0.5,
    genre_palette: { Drama: '#808080' },
    feature_weights: { text: 1, genre: 1, lang: 0 },
    z_range: [1990, 2000],
    xy_range: { x: [-1, 1], y: [-1, 1] },
  },
  movies: [
    {
      x: 0,
      y: 0,
      z: 1995,
      size: 1,
      emissive: 0.5,
      genre_color: [0.5, 0.5, 0.5],
      title: 'Fixture',
      original_title: 'Fixture',
      overview: '',
      tagline: null,
      release_date: '1995-01-01',
      genres: ['Drama'],
      original_language: 'en',
      vote_count: 1,
      vote_average: 7,
      popularity: 1,
      imdb_rating: null,
      imdb_votes: null,
      runtime: null,
      revenue: 0,
      budget: 0,
      production_countries: [],
      production_companies: [],
      spoken_languages: [],
      cast: [],
      director: [],
      writers: [],
      producers: [],
      director_of_photography: [],
      music_composer: [],
      poster_url: '',
      id: 1,
      imdb_id: null,
    },
  ],
} as const satisfies GalaxyData
